import type { Metadata } from 'next'
import { Noto_Sans_TC } from 'next/font/google'
import './globals.css'

const NotoSansTC = Noto_Sans_TC({
  weight: ['400', '500', '700'],
  display: 'swap',
  variable: '--font-noto-sans-tc',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body
        className={`${NotoSansTC.variable} ${NotoSansTC.className} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
